#!/usr/bin/env node
/*
 * Static blog generator.
 *
 * Reads content/blog/*.md (front matter + Markdown) and writes plain HTML:
 *   public/blog/index.html            - article list, newest first
 *   public/blog/<slug>/index.html     - one page per article
 * and refreshes the managed block in public/sitemap.xml.
 *
 * Why static HTML: the site is a client-rendered SPA, and social crawlers
 * (LinkedIn, Reddit, Telegram) do not run JavaScript, so every article needs
 * its own <title> and Open Graph tags in the served HTML.
 *
 * Drafts (`draft: true`) are skipped unless `--drafts` is passed. When
 * included they get <meta name="robots" content="noindex"> and are never
 * added to the sitemap.
 *
 * Usage: node scripts/build-blog.js [--drafts]
 */
const fs = require("fs");
const path = require("path");
const matter = require("gray-matter");
const { marked } = require("marked");

const ROOT = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "content", "blog");
const OUT_DIR = path.join(ROOT, "public", "blog");
const SITEMAP = path.join(ROOT, "public", "sitemap.xml");
const ORIGIN = "https://www.wtfgames.com.ua"; // same origin as sitemap.xml and index.html
const SITE_NAME = "WTFGames";
const SM_START = "<!-- blog:start (generated by scripts/build-blog.js, do not edit) -->";
const SM_END = "<!-- blog:end -->";

// Font Awesome brand icons are inlined so blog pages do not need the CRA bundle or the font.
function brandIcon(name) {
    const file = path.join(ROOT, "node_modules", "@fortawesome", "fontawesome-free", "svgs", "brands", `${name}.svg`);
    return fs
        .readFileSync(file, "utf8")
        .replace(/<!--[\s\S]*?-->/g, "")
        .replace("<svg ", '<svg aria-hidden="true" focusable="false" ')
        .trim();
}
const SOCIAL = [
    ["Instagram", "instagram", "https://www.instagram.com/wtfgames_community/"],
    ["LinkedIn", "linkedin", "https://www.linkedin.com/groups/8502086/"],
    ["Twitter", "twitter", "https://x.com/wtfgames14?s=21"],
];

const includeDrafts = process.argv.includes("--drafts");

const esc = (value) =>
    String(value)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");

function fail(file, message) {
    throw new Error(`${path.relative(ROOT, file)}: ${message}`);
}

function toIsoDate(value, file) {
    const date = value instanceof Date ? value : new Date(String(value));
    if (Number.isNaN(date.getTime())) fail(file, `invalid date "${value}"`);
    return date.toISOString().slice(0, 10);
}

function formatDate(iso) {
    return new Date(`${iso}T00:00:00Z`).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
        timeZone: "UTC",
    });
}

/** Resolve a path relative to the article folder into a root-relative URL. */
function assetUrl(slug, src) {
    if (/^([a-z][a-z0-9+.-]*:|\/\/|\/|#)/i.test(src)) return src;
    return `/blog/${slug}/${src}`;
}

function loadArticles() {
    if (!fs.existsSync(CONTENT_DIR)) return [];
    const articles = [];
    for (const name of fs.readdirSync(CONTENT_DIR).filter((f) => f.endsWith(".md"))) {
        const file = path.join(CONTENT_DIR, name);
        const { data, content } = matter(fs.readFileSync(file, "utf8"));
        for (const key of ["title", "description", "date", "slug", "cover"]) {
            if (!data[key]) fail(file, `missing front matter field "${key}"`);
        }
        if (data.draft !== true && /TODO/.test(content)) fail(file, "published article still contains a TODO marker");
        const slug = String(data.slug);
        if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug)) fail(file, `invalid slug "${slug}"`);
        articles.push({
            title: String(data.title),
            description: String(data.description),
            date: toIsoDate(data.date, file),
            slug,
            cover: assetUrl(slug, String(data.cover)),
            coverAlt: data.coverAlt ? String(data.coverAlt) : String(data.title),
            lang: data.lang ? String(data.lang) : "en",
            tags: Array.isArray(data.tags) ? data.tags.map(String) : [],
            draft: data.draft === true,
            body: content,
        });
    }
    const slugs = new Set();
    for (const a of articles) {
        if (slugs.has(a.slug)) throw new Error(`duplicate slug "${a.slug}"`);
        slugs.add(a.slug);
    }
    return articles
        .filter((a) => includeDrafts || !a.draft)
        .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : a.slug.localeCompare(b.slug)));
}

function renderBody(article) {
    let html = marked.parse(article.body, { gfm: true });
    // Root-relative image URLs, lazy loading, scrollable tables.
    html = html.replace(/<img ([^>]*?)src="([^"]+)"/g, (_m, pre, src) => {
        return `<img loading="lazy" decoding="async" ${pre}src="${esc(assetUrl(article.slug, src.replace(/&amp;/g, "&")))}"`;
    });
    html = html.replace(/<table>/g, '<div class="table-wrap"><table>').replace(/<\/table>/g, "</table></div>");
    return html;
}

const STYLES = `
*,*::before,*::after{box-sizing:border-box}
html{-webkit-text-size-adjust:100%}
body{margin:0;min-height:100vh;display:flex;flex-direction:column;background:#212529;color:#dee2e6;
font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen,Ubuntu,Cantarell,"Fira Sans","Droid Sans","Helvetica Neue",sans-serif;
font-size:1.0625rem;line-height:1.7;-webkit-font-smoothing:antialiased}
a{color:#65a3db}a:hover{color:#8bbbe6}
a:focus-visible,button:focus-visible{outline:2px solid #65a3db;outline-offset:2px}
main{flex:1 0 auto;width:100%;max-width:720px;margin:0 auto;padding:40px 16px 64px}
h1,h2,h3{color:#fff;line-height:1.25}
h1{font-size:clamp(1.75rem,5vw,2.5rem);margin:0 0 .5rem}
h2{font-size:1.5rem;margin:2.25em 0 .6em}
h3{font-size:1.2rem;margin:1.75em 0 .5em}
.meta{color:#adb5bd;font-size:.95rem;margin:0 0 1.5rem}
.tags{list-style:none;padding:0;margin:0 0 1.5rem;display:flex;flex-wrap:wrap;gap:6px}
.tags li{background:#343a40;border-radius:999px;padding:0 10px;font-size:.85rem;color:#ced4da}
.draft-note{background:#4a3b00;border:1px solid #ffc107;color:#ffe69c;border-radius:6px;padding:12px 16px;margin:0 0 1.5rem;font-size:.95rem}
.badge{display:inline-block;background:#ffc107;color:#212529;border-radius:4px;padding:0 6px;font-size:.75rem;font-weight:700;text-transform:uppercase;vertical-align:middle}
.cover{margin:0 0 2rem}
img{max-width:100%;height:auto;border-radius:6px}
figure{margin:1.5rem 0}figcaption{color:#adb5bd;font-size:.9rem;margin-top:.5rem}
p,ul,ol{margin:0 0 1.1em}li{margin-bottom:.3em}
code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.9em;background:#2b3035;border-radius:4px;padding:.1em .35em}
pre{background:#16191c;border:1px solid #343a40;border-radius:6px;padding:14px 16px;overflow-x:auto;margin:0 0 1.25em}
pre code{background:none;padding:0;font-size:.85rem;line-height:1.5}
.table-wrap{overflow-x:auto;margin:0 0 1.25em}
table{border-collapse:collapse;min-width:100%;font-size:.95rem}
th,td{border:1px solid #495057;padding:8px 12px;text-align:left;vertical-align:top}
th{background:#2b3035;color:#fff}
blockquote{margin:0 0 1.25em;padding:.25em 1em;border-inline-start:4px solid #65a3db;color:#ced4da}
hr{border:0;border-top:1px solid #343a40;margin:2.5rem 0}
.post-list{list-style:none;margin:0;padding:0;display:grid;gap:28px}
.post-card h2{font-size:1.35rem;margin:.6rem 0 .25rem}
.post-card h2 a{color:#fff;text-decoration:none}.post-card h2 a:hover{color:#8bbbe6}
.post-card p{margin:0 0 .4em}
.post-card img{display:block;width:100%;aspect-ratio:1200/630;object-fit:cover}
.container{width:100%;margin:0 auto;padding:0 12px}
@media (min-width:576px){.container{max-width:540px}}
@media (min-width:768px){.container{max-width:720px}}
@media (min-width:992px){.container{max-width:960px}}
@media (min-width:1200px){.container{max-width:1140px}}
@media (min-width:1400px){.container{max-width:1320px}}
.site-header,.site-footer{background:#212529;font-family:system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue","Noto Sans","Liberation Sans",Arial,sans-serif;font-size:16px;line-height:1.5}
.site-header ul,.site-footer ul{list-style:none;margin:0;padding:0}
.hbar{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;padding-top:8px;padding-bottom:8px}
.brand{display:inline-block;padding:5px 0;margin-right:16px;line-height:inherit}
.brand img{display:block;height:40px;width:auto;max-width:clamp(160px,70vw,288px);border-radius:0}
.nav-toggle{display:none;font-size:1.25rem;line-height:1;padding:4px 12px;background:none;color:rgba(255,255,255,.55);border:1px solid rgba(255,255,255,.1);border-radius:6px;cursor:pointer}
.js .nav-toggle{display:block}
.nav-toggle-icon{display:block;width:1.5em;height:1.5em;background:url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='rgba%28255, 255, 255, 0.55%29' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e") center/100% no-repeat}
.nav-menu{flex-basis:100%;flex-grow:1}
.js .nav-menu{display:none}
.js .nav-menu.open{display:block}
.site-header .nav-link{display:block;padding:8px 0;color:rgba(255,255,255,.55);text-decoration:none}
.site-header .nav-link:hover{color:rgba(255,255,255,.75)}
.site-header .nav-link[aria-current="page"]{color:#fff}
.site-header .nav-link svg{height:1em;width:auto;vertical-align:-.125em;fill:currentColor}
@media (min-width:992px){
.nav-toggle,.js .nav-toggle{display:none}
.nav-menu,.js .nav-menu{display:flex;flex-basis:auto;align-items:center;margin-left:auto}
.nav-main{display:flex;margin-right:16px}
.nav-social{display:flex}
.site-header .nav-link{padding:8px}
}
.fbar{display:flex;flex-direction:column;align-items:center;justify-content:space-between;padding-top:24px;padding-bottom:24px;color:#f8f9fa}
.fcopy{margin-bottom:8px;text-align:center}
.fcopy small{font-size:.875em}
.site-footer ul{display:flex;gap:16px}
.site-footer a{color:#f8f9fa;text-decoration:none}
@media (min-width:768px){.fbar{flex-direction:row}.fcopy{margin-bottom:0;text-align:start}}
@media (prefers-reduced-motion:no-preference){a{transition:color .15s}}
`;

function layout({ lang, title, description, canonical, robots, head, bodyHtml, current }) {
    const navLink = (href, label) =>
        `<li><a class="nav-link" href="${href}"${current === href ? ' aria-current="page"' : ""}>${label}</a></li>`;
    return `<!DOCTYPE html>
<html lang="${esc(lang)}">
<head>
<meta charset="utf-8">
<script>document.documentElement.classList.add("js")</script>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#1E2033">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${esc(canonical)}">
${robots ? `<meta name="robots" content="${robots}">\n` : ""}<link rel="icon" href="/favicon.ico">
${head}
<style>${STYLES}</style>
</head>
<body>
<header class="site-header">
<nav aria-label="Main">
<div class="container hbar">
<a class="brand" href="/"><img src="/wtfgames_logo.svg" alt="${SITE_NAME}" width="288" height="40"></a>
<button class="nav-toggle" type="button" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation"><span class="nav-toggle-icon"></span></button>
<div class="nav-menu" id="navbarContent">
<ul class="nav-main">
${navLink("/about", "About Us")}
${navLink("/games", "Games")}
${navLink("/applications", "Applications")}
${navLink("/blog/", "Blog")}
</ul>
<ul class="nav-social">
${SOCIAL.map(([label, icon, href]) => `<li><a class="nav-link" href="${href}" target="_blank" rel="noopener noreferrer" aria-label="${label}">${brandIcon(icon)}</a></li>`).join("\n")}
</ul>
</div>
</div>
</nav>
</header>
${bodyHtml}
<footer class="site-footer">
<div class="container fbar">
<div class="fcopy"><small>&copy; ${new Date().getFullYear()} ${SITE_NAME}. All rights reserved.</small></div>
<ul>
<li><a href="/blog/">Blog</a></li>
<li><a href="/privacy">Privacy Policy</a></li>
<li><a href="/terms">Terms of Service</a></li>
<li><a href="/contact">Contact</a></li>
</ul>
</div>
</footer>
<script>
(function(){var b=document.querySelector(".nav-toggle"),m=document.getElementById("navbarContent");
b.addEventListener("click",function(){var o=m.classList.toggle("open");b.setAttribute("aria-expanded",o)});})();
</script>
</body>
</html>
`;
}

function articleHtml(a) {
    const url = `${ORIGIN}/blog/${a.slug}/`;
    const image = a.cover.startsWith("http") ? a.cover : ORIGIN + a.cover;
    const jsonLd = {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        headline: a.title,
        description: a.description,
        datePublished: a.date,
        image: [image],
        mainEntityOfPage: url,
        inLanguage: a.lang,
        author: { "@type": "Organization", name: SITE_NAME },
        publisher: { "@type": "Organization", name: SITE_NAME, logo: { "@type": "ImageObject", url: `${ORIGIN}/logo512.png` } },
    };
    const head = [
        `<meta property="og:type" content="article">`,
        `<meta property="og:site_name" content="${SITE_NAME}">`,
        `<meta property="og:title" content="${esc(a.title)}">`,
        `<meta property="og:description" content="${esc(a.description)}">`,
        `<meta property="og:url" content="${esc(url)}">`,
        `<meta property="og:image" content="${esc(image)}">`,
        `<meta property="article:published_time" content="${a.date}">`,
        ...a.tags.map((t) => `<meta property="article:tag" content="${esc(t)}">`),
        `<meta name="twitter:card" content="summary_large_image">`,
        `<meta name="twitter:title" content="${esc(a.title)}">`,
        `<meta name="twitter:description" content="${esc(a.description)}">`,
        `<meta name="twitter:image" content="${esc(image)}">`,
        // "<" is escaped so front-matter text can never close the script element.
        `<script type="application/ld+json">${JSON.stringify(jsonLd).replace(/</g, "\\u003c")}</script>`,
    ].join("\n");
    const tags = a.tags.length
        ? `<ul class="tags" aria-label="Tags">${a.tags.map((t) => `<li>${esc(t)}</li>`).join("")}</ul>`
        : "";
    const draftNote = a.draft
        ? `<p class="draft-note" role="note"><span class="badge">Draft</span> This article is not published. It is hidden from search engines and the sitemap, and is only generated for local preview.</p>`
        : "";
    const bodyHtml = `<main>
<article>
${draftNote}
<h1>${esc(a.title)}</h1>
<p class="meta"><time datetime="${a.date}">${formatDate(a.date)}</time></p>
${tags}
<figure class="cover"><img src="${esc(a.cover)}" alt="${esc(a.coverAlt)}" width="1200" height="630"></figure>
${renderBody(a)}
</article>
<hr>
<p><a href="/blog/">&larr; All articles</a></p>
</main>`;
    return layout({
        lang: a.lang,
        title: `${a.title} | ${SITE_NAME}`,
        description: a.description,
        canonical: url,
        robots: a.draft ? "noindex, nofollow" : "",
        head,
        bodyHtml,
        current: "/blog/",
    });
}

function indexHtml(articles) {
    const url = `${ORIGIN}/blog/`;
    const description = "Articles from WTFGames: practical notes on our apps and the problems they solve.";
    const head = [
        `<meta property="og:type" content="website">`,
        `<meta property="og:site_name" content="${SITE_NAME}">`,
        `<meta property="og:title" content="Blog | ${SITE_NAME}">`,
        `<meta property="og:description" content="${esc(description)}">`,
        `<meta property="og:url" content="${url}">`,
        `<meta property="og:image" content="${ORIGIN}/logo512.png">`,
        `<meta name="twitter:card" content="summary">`,
    ].join("\n");
    const items = articles
        .map(
            (a) => `<li class="post-card"><article>
<a href="/blog/${a.slug}/" tabindex="-1" aria-hidden="true"><img src="${esc(a.cover)}" alt="" width="1200" height="630" loading="lazy" decoding="async"></a>
<h2><a href="/blog/${a.slug}/">${esc(a.title)}</a>${a.draft ? ' <span class="badge">Draft</span>' : ""}</h2>
<p class="meta"><time datetime="${a.date}">${formatDate(a.date)}</time></p>
<p>${esc(a.description)}</p>
</article></li>`
        )
        .join("\n");
    const bodyHtml = `<main>
<h1>Blog</h1>
${articles.length ? `<ul class="post-list">\n${items}\n</ul>` : "<p>No articles yet.</p>"}
</main>`;
    // An index that only lists drafts must not be indexed either.
    const allDrafts = articles.length > 0 && articles.every((a) => a.draft);
    return layout({
        lang: "en",
        title: `Blog | ${SITE_NAME}`,
        description,
        canonical: url,
        robots: allDrafts || articles.length === 0 ? "noindex, follow" : "",
        head,
        bodyHtml,
        current: "/blog/",
    });
}

function cleanOutput() {
    // Remove only previously generated HTML; committed assets (images) stay.
    if (!fs.existsSync(OUT_DIR)) return;
    fs.rmSync(path.join(OUT_DIR, "index.html"), { force: true });
    for (const entry of fs.readdirSync(OUT_DIR, { withFileTypes: true })) {
        if (entry.isDirectory()) fs.rmSync(path.join(OUT_DIR, entry.name, "index.html"), { force: true });
    }
}

function updateSitemap(published) {
    const xml = fs.readFileSync(SITEMAP, "utf8");
    const start = xml.indexOf(SM_START);
    const end = xml.indexOf(SM_END);
    if (start === -1 || end === -1 || end < start) {
        throw new Error(`public/sitemap.xml must contain the markers:\n${SM_START}\n${SM_END}`);
    }
    const entry = (loc, lastmod, changefreq, priority) =>
        `    <url>\n        <loc>${loc}</loc>\n        <lastmod>${lastmod}</lastmod>\n        <changefreq>${changefreq}</changefreq>\n        <priority>${priority}</priority>\n    </url>\n`;
    let block = "";
    if (published.length) {
        block += entry(`${ORIGIN}/blog/`, published[0].date, "weekly", "0.6");
        for (const a of published) block += entry(`${ORIGIN}/blog/${a.slug}/`, a.date, "monthly", "0.7");
    }
    const next = `${xml.slice(0, start)}${SM_START}\n${block}    ${xml.slice(end)}`;
    if (next !== xml) fs.writeFileSync(SITEMAP, next);
}

function main() {
    const articles = loadArticles();
    cleanOutput();
    fs.mkdirSync(OUT_DIR, { recursive: true });
    for (const a of articles) {
        const dir = path.join(OUT_DIR, a.slug);
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(path.join(dir, "index.html"), articleHtml(a));
    }
    fs.writeFileSync(path.join(OUT_DIR, "index.html"), indexHtml(articles));
    updateSitemap(articles.filter((a) => !a.draft));
    const drafts = articles.filter((a) => a.draft).length;
    console.log(
        `blog: ${articles.length} article(s) generated (${drafts} draft${drafts === 1 ? "" : "s"}${includeDrafts ? ", drafts included" : ", drafts excluded"})`
    );
}

main();
